type Query {
    videos(
        pagination: Pagination = {}
        search: String
        sort: Sort
    ): [Video]
    video(video_id: ID!): Video
}

type Mutation {
    addVideo(video_name: String! video_file: Upload!): Response!
    
    updateVideo( video_id: String! video_name: String! ): Response!

    deleteVideo( video_id: String! ): Response!
}

type Video {
    user_id: ID!
    video_id: ID!
    video_name: String!
    video_link: String!
    video_date: String!
    video_size: String!
}